sudo: false
dist: trusty
language: node_js

cache:
  directories:
    - node_modules

addons:
  chrome: stable

node_js:
  - "6"
  - "7"
  - "8"

matrix:
  fast_finish: true

before_install:
  - npm install npm@5 -g
  - npm cache verify
  - npm prune
  - npm update

before_script:
  - node ./node_modules/protractor/bin/webdriver-manager update

install:
  - npm install

script:
  - npm run ci:travis
